name: CLI

on: [push, pull_request]

jobs:
  library:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9, '3.10', '3.11']
    steps:
    - run: |
        pip install -U polyaxon
        polyaxon version
  tests:
#    if: github.event.comment.body == 'test cli'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        which python
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r cli/cli/requirements/test.txt
    - name: traceml
      run: pip install -e traceml/traceml
    - name: hypertune
      run: pip install -e hypertune/hypertune
    - name: Install dev libraries
      run: |
        cd cli
        export USE_LOCAL_PACKAGES="true" && pip install --upgrade --editable "cli[dev,k8s_async,fsspec,init,sidecar]"
    - name: Test with pytest
      run: |
        cd cli/cli
        pytest -vv
