name: Polyaxon Sandbox

on: [push, pull_request]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: build
      run: |
        cmd/rebuild
    - name: test-polycommon
      run: |
        cmd/test platform/polycommon module
    - name: test-coredb
      run: |
        cmd/test platform/coredb module --create-db
    - name: test-coreapi
      run: |
        cmd/test platform/coreapi
